version: '3.1'

services:
  app:
    build: .
    container_name: "rick_morty_api"
    command: sh -c "npx prisma migrate deploy && yarn start"
    ports:
      - 5000:5000
    volumes:
      - .:/usr/src/app
    links:
      - db
    depends_on:
      - db
    environment:
      PG_USER: ${PG_USER}
      PG_PASS: ${PG_PASS}
      PG_DB: ${PG_DB}
  db:
    image: postgres
    restart: always
    ports:
      - 5432:5432
    environment:
      POSTGRES_PASSWORD: ${PG_PASS}
      POSTGRES_USER: ${PG_USER}
      POSTGRES_DB: ${PG_DB}
    volumes:
      - ./pgdata:/var/lib/postgresql/data
  pgadmin:
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: 'admin@gmail.com'
      PGADMIN_DEFAULT_PASSWORD: 'admin'
    ports:
      - 5050:80
    depends_on:
      - postgresql
networks:
  overlay:
