version: '3.7'

services:
  api:
    container_name: rick_morty_api
    build:
      context: .
      target: development
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules
    ports:
      - ${PORT}:${PORT}
      - 9229:9229
    command: yarn start:prod
    env_file:
      - .env
    networks:
      - backend
    depends_on:
      - postgres
  postgres:
    container_name: rick_morty_db
    image: postgres:9.6-alpine
    networks:
      - backend
    environment:
      POSTGRES_PASSWORD: ${PG_PASS}
      POSTGRES_USER: ${PG_USER}
      POSTGRES_DB: ${PG_DB}
      PG_DATA: /var/lib/postgresql/data
    ports:
      - 5432:5432
    volumes:
      - api_db_data:/var/lib/postgresql/data
networks:
  backend:
volumes:
  api_db_data:
